# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 900)
        Form.setMinimumSize(QtCore.QSize(900, 900))
        Form.setMaximumSize(QtCore.QSize(900, 900))
        Form.setStyleSheet("/*\n"
"Ubuntu Style Sheet for QT Applications\n"
"Author: Jaime A. Quiroga P.\n"
"Company: GTRONICK\n"
"Last updated: 01/10/2021 (dd/mm/yyyy), 15:18.\n"
"Available at: https://github.com/GTRONICK/QSS/blob/master/Ubuntu.qss\n"
"*/\n"
"QMainWindow {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QCheckBox {\n"
"    padding:2px;\n"
"}\n"
"QCheckBox:hover {\n"
"    border:1px solid rgb(255,150,60);\n"
"    border-radius:4px;\n"
"    padding: 1px;\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(190, 90, 50, 50), stop:1 rgba(250, 130, 40, 50));\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border:1px solid rgb(246, 134, 86);\n"
"    border-radius:4px;\n"
"      background-color:rgb(246, 134, 86)\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-width:1px solid rgb(246, 134, 86);\n"
"    border-radius:4px;\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QColorDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background: #ffffff;\n"
"}\n"
"QComboBox:editable {\n"
"    selection-color:rgb(81,72,65);\n"
"    selection-background-color: #ffffff;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    selection-color: #ffffff;\n"
"    selection-background-color: rgb(246, 134, 86);\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color:  #1e1d23;    \n"
"}\n"
"QDateTimeEdit, QDateEdit, QDoubleSpinBox, QFontComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"\n"
"QLabel,QLineEdit {\n"
"    color:rgb(17,17,17);\n"
"}\n"
"QLineEdit {\n"
"    background-color:rgb(255,255,255);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QMenuBar {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item {\n"
"    padding-top:4px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    padding-top:2px;\n"
"    padding-left:2px;\n"
"    padding-right:2px;\n"
"    border-top-width:2px;\n"
"    border-left-width:2px;\n"
"    border-right-width:2px;\n"
"    border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-style:solid;\n"
"    background-color:rgb(65,64,59);\n"
"    border-top-color: rgb(47,47,44);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"}\n"
"QMenu {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    padding:4px 10px 4px 20px;\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border-style:solid;\n"
"    border-width:3px;\n"
"    padding:4px 7px 4px 17px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPlainTextEdit {\n"
"    border: 1px solid transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"    background-color: #FFFFFF;\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px inset rgb(150,150,150); \n"
"    border-radius: 10px;\n"
"    background-color:rgb(221,221,219);\n"
"}\n"
"QProgressBar::chunk:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border:1px solid;\n"
"    border-radius:8px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPushButton{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-bottom-color: rgb(150,150,150);\n"
"    border-right-color: rgb(165,165,165);\n"
"    border-left-color: rgb(165,165,165);\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-style: solid;\n"
"    padding: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:default{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:pressed{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-width: 1px;\n"
"    border-top-color: rgba(255,150,60,200);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-bottom-color: rgba(200,70,20,200);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    color:rgb(174,167,159);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(200, 200, 200, 255), stop:1 rgba(230, 230, 230, 255));\n"
"}\n"
"QRadioButton {\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgba(246, 134, 86, 255);\n"
"    color: #a9b7c6;\n"
"    background-color:rgba(246, 134, 86, 255);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(246, 134, 86);\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QScrollArea {\n"
"    color: white;\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QSlider::groove {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal, QSlider::add-page:vertical {\n"
"     background: white;\n"
"}\n"
"QSlider::sub-page:horizontal, QSlider::sub-page:vertical {\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QStatusBar, QSpinBox {\n"
"    color:rgb(81,72,65);\n"
"}\n"
"QSpinBox {\n"
"    background-color: #ffffff;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    max-height: 20px;\n"
"    border: 1px transparent;\n"
"    margin: 0px 20px 0px 20px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"      border: 1px solid rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"      border: 1px solid rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"      border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"      border-bottom-left-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"    border: 1px transparent grey;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"     background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"     background: none;\n"
"} \n"
"QScrollBar:vertical {\n"
"    max-width: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: 1px solid;\n"
"    border-color: rgb(207,207,207);\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(255,150,60);\n"
"      border-bottom-right-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"      border: 1px solid rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"      border: 1px solid rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"     height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"    border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"      border: 1px transparent grey;\n"
"      border-bottom-left-radius: 3px;\n"
"      border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:rgb(247,246,246);\n"
"}\n"
"QTabWidget::pane {\n"
"    border-color: rgb(180,180,180);\n"
"    background-color:rgb(247,246,246);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    padding-bottom:2px;\n"
"    padding-top:2px;\n"
"    color:rgb(81,72,65);\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(221,218,217,255), stop:1 rgba(240,239,238,255));\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-left-color: rgb(180,180,180);\n"
"    border-right-color: rgb(180,180,180);\n"
"    border-bottom-color: transparent;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      background-color:rgb(247,246,246);\n"
"      margin-left: 0px;\n"
"      margin-right: 1px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 1px;\n"
"    margin-right: 1px;\n"
"}\n"
"QTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color:transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QTimeEdit, QToolBox, QToolBox::tab, QToolBox::tab:selected {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.window_tab = QtWidgets.QTabWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.window_tab.setFont(font)
        self.window_tab.setAutoFillBackground(False)
        self.window_tab.setObjectName("window_tab")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget.setMaximumSize(QtCore.QSize(250, 100))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget.verticalHeader().setMinimumSectionSize(20)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.groupBox = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 9000))
        self.groupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.checkBox_gunhao = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_gunhao.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.checkBox_gunhao.setObjectName("checkBox_gunhao")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 300, 54, 12))
        self.label_6.setObjectName("label_6")
        self.pushButton_saveConfig = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_saveConfig.setGeometry(QtCore.QRect(10, 360, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_saveConfig.setFont(font)
        self.pushButton_saveConfig.setObjectName("pushButton_saveConfig")
        self.checkBox_gunjuese = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_gunjuese.setGeometry(QtCore.QRect(80, 20, 61, 16))
        self.checkBox_gunjuese.setObjectName("checkBox_gunjuese")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 260, 151, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_steamPath_charNum = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_steamPath_charNum.setGeometry(QtCore.QRect(160, 250, 41, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.lineEdit_steamPath_charNum.setFont(font)
        self.lineEdit_steamPath_charNum.setObjectName("lineEdit_steamPath_charNum")
        self.lineEdit_steamPath = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_steamPath.setGeometry(QtCore.QRect(10, 320, 201, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.lineEdit_steamPath.setFont(font)
        self.lineEdit_steamPath.setObjectName("lineEdit_steamPath")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(100, 366, 101, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.checkBox_chaosGate = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_chaosGate.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.checkBox_chaosGate.setObjectName("checkBox_chaosGate")
        self.checkBox_noAncient = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_noAncient.setGeometry(QtCore.QRect(10, 230, 91, 16))
        self.checkBox_noAncient.setObjectName("checkBox_noAncient")
        self.checkBox_onlyEnterGame = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_onlyEnterGame.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.checkBox_onlyEnterGame.setObjectName("checkBox_onlyEnterGame")
        self.checkBox_takeBusMode = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_takeBusMode.setGeometry(QtCore.QRect(110, 40, 71, 16))
        self.checkBox_takeBusMode.setObjectName("checkBox_takeBusMode")
        self.checkBox_cube = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_cube.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.checkBox_cube.setObjectName("checkBox_cube")
        self.checkBox_guardian = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_guardian.setGeometry(QtCore.QRect(90, 130, 81, 16))
        self.checkBox_guardian.setObjectName("checkBox_guardian")
        self.checkBox_homeFarm = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_homeFarm.setGeometry(QtCore.QRect(180, 130, 51, 16))
        self.checkBox_homeFarm.setObjectName("checkBox_homeFarm")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 110, 54, 12))
        self.label_10.setObjectName("label_10")
        self.checkBox_newEventTask = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_newEventTask.setGeometry(QtCore.QRect(10, 90, 161, 16))
        self.checkBox_newEventTask.setObjectName("checkBox_newEventTask")
        self.checkBox_fish = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_fish.setGeometry(QtCore.QRect(90, 70, 51, 16))
        self.checkBox_fish.setObjectName("checkBox_fish")
        self.checkBox_unionSilverDonation = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_unionSilverDonation.setGeometry(QtCore.QRect(100, 230, 101, 16))
        self.checkBox_unionSilverDonation.setObjectName("checkBox_unionSilverDonation")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 150, 91, 16))
        self.label_15.setObjectName("label_15")
        self.checkBox_gem = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_gem.setGeometry(QtCore.QRect(10, 170, 51, 16))
        self.checkBox_gem.setObjectName("checkBox_gem")
        self.checkBox_fishMat = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_fishMat.setGeometry(QtCore.QRect(60, 170, 41, 16))
        self.checkBox_fishMat.setObjectName("checkBox_fishMat")
        self.checkBox_chaosGateMat = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_chaosGateMat.setGeometry(QtCore.QRect(100, 170, 111, 16))
        self.checkBox_chaosGateMat.setObjectName("checkBox_chaosGateMat")
        self.lineEdit_receiveMailCharName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_receiveMailCharName.setGeometry(QtCore.QRect(90, 190, 111, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.lineEdit_receiveMailCharName.setFont(font)
        self.lineEdit_receiveMailCharName.setObjectName("lineEdit_receiveMailCharName")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 200, 81, 16))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_5.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.tableWidget_info = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_info.setMaximumSize(QtCore.QSize(182, 16777215))
        self.tableWidget_info.setObjectName("tableWidget_info")
        self.tableWidget_info.setColumnCount(1)
        self.tableWidget_info.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info.setHorizontalHeaderItem(0, item)
        self.tableWidget_info.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.tableWidget_info)
        self.textBrowser_log = QtWidgets.QTextBrowser(self.tab_6)
        self.textBrowser_log.setObjectName("textBrowser_log")
        self.horizontalLayout.addWidget(self.textBrowser_log)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tab_6)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidget_daixuanrenwu = QtWidgets.QListWidget(self.tab_6)
        self.listWidget_daixuanrenwu.setMaximumSize(QtCore.QSize(120, 16777215))
        self.listWidget_daixuanrenwu.setObjectName("listWidget_daixuanrenwu")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_daixuanrenwu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_daixuanrenwu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_daixuanrenwu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_daixuanrenwu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_daixuanrenwu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_daixuanrenwu.addItem(item)
        self.verticalLayout.addWidget(self.listWidget_daixuanrenwu)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_allAdd = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_allAdd.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_allAdd.setObjectName("pushButton_allAdd")
        self.verticalLayout_3.addWidget(self.pushButton_allAdd)
        self.pushButton_add = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_add.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout_3.addWidget(self.pushButton_add)
        self.pushButton_del = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_del.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_del.setObjectName("pushButton_del")
        self.verticalLayout_3.addWidget(self.pushButton_del)
        self.pushButton_delAll = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_delAll.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_delAll.setObjectName("pushButton_delAll")
        self.verticalLayout_3.addWidget(self.pushButton_delAll)
        self.pushButton_up = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_up.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_up.setObjectName("pushButton_up")
        self.verticalLayout_3.addWidget(self.pushButton_up)
        self.pushButton_down = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_down.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_down.setObjectName("pushButton_down")
        self.verticalLayout_3.addWidget(self.pushButton_down)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listWidget_yixuanrenwu = QtWidgets.QListWidget(self.tab_6)
        self.listWidget_yixuanrenwu.setMaximumSize(QtCore.QSize(120, 16777215))
        self.listWidget_yixuanrenwu.setObjectName("listWidget_yixuanrenwu")
        self.verticalLayout_2.addWidget(self.listWidget_yixuanrenwu)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_open_source_file = QtWidgets.QPushButton(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.pushButton_open_source_file.setFont(font)
        self.pushButton_open_source_file.setObjectName("pushButton_open_source_file")
        self.verticalLayout_4.addWidget(self.pushButton_open_source_file)
        self.pushButton_open_account_file = QtWidgets.QPushButton(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.pushButton_open_account_file.setFont(font)
        self.pushButton_open_account_file.setObjectName("pushButton_open_account_file")
        self.verticalLayout_4.addWidget(self.pushButton_open_account_file)
        self.tabWidget = QtWidgets.QTabWidget(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_start = QtWidgets.QPushButton(self.tab)
        self.pushButton_start.setEnabled(True)
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(26)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout_6.addWidget(self.pushButton_start)
        self.pushButton_stop = QtWidgets.QPushButton(self.tab)
        self.pushButton_stop.setEnabled(True)
        self.pushButton_stop.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(26)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.verticalLayout_6.addWidget(self.pushButton_stop)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.setStretch(0, 2)
        self.verticalLayout_8.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.window_tab.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.acc_state_table = QtWidgets.QTableWidget(self.tab_7)
        self.acc_state_table.setStyleSheet("QTableView::item:selected {\n"
"    background-color: #FFCCCC; /* 淡红色 */\n"
"    color: black; /* 文字颜色为黑色 */\n"
"}\n"
"")
        self.acc_state_table.setObjectName("acc_state_table")
        self.acc_state_table.setColumnCount(8)
        self.acc_state_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.acc_state_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.acc_state_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.acc_state_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.acc_state_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.acc_state_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.acc_state_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.acc_state_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.acc_state_table.setHorizontalHeaderItem(7, item)
        self.acc_state_table.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_7.addWidget(self.acc_state_table)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.search_btn = QtWidgets.QPushButton(self.tab_7)
        self.search_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.search_btn.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.search_btn.setFont(font)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_7.addWidget(self.search_btn)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.setStretch(0, 100)
        self.verticalLayout_7.setStretch(1, 1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.window_tab.addTab(self.tab_7, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_9.addWidget(self.textBrowser)
        self.window_tab.addTab(self.tab_2, "")
        self.horizontalLayout_4.addWidget(self.window_tab)

        self.retranslateUi(Form)
        self.window_tab.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "当前任务"))
        self.groupBox.setTitle(_translate("Form", "功能设置"))
        self.checkBox_gunhao.setText(_translate("Form", "滚号"))
        self.label_6.setText(_translate("Form", "steam路径"))
        self.pushButton_saveConfig.setText(_translate("Form", "保存配置"))
        self.checkBox_gunjuese.setText(_translate("Form", "滚角色"))
        self.label_7.setText(_translate("Form", "角色数量(只滚角色才有用)"))
        self.label_9.setText(_translate("Form", "<===设置完点保存"))
        self.checkBox_chaosGate.setText(_translate("Form", "混沌之门"))
        self.checkBox_noAncient.setText(_translate("Form", "不分解古代"))
        self.checkBox_onlyEnterGame.setText(_translate("Form", "只进入游戏"))
        self.checkBox_takeBusMode.setText(_translate("Form", "坐车模式"))
        self.checkBox_cube.setText(_translate("Form", "魔方派遣"))
        self.checkBox_guardian.setText(_translate("Form", "加迪恩派遣"))
        self.checkBox_homeFarm.setText(_translate("Form", "种植"))
        self.label_10.setText(_translate("Form", "家园任务"))
        self.checkBox_newEventTask.setText(_translate("Form", "新活动任务(只能单独做)"))
        self.checkBox_fish.setText(_translate("Form", "钓鱼"))
        self.checkBox_unionSilverDonation.setText(_translate("Form", "公会银币捐献"))
        self.label_15.setText(_translate("Form", "需要邮寄的材料"))
        self.checkBox_gem.setText(_translate("Form", "宝石"))
        self.checkBox_fishMat.setText(_translate("Form", "鱼"))
        self.checkBox_chaosGateMat.setText(_translate("Form", "混沌之门及地牢"))
        self.label_16.setText(_translate("Form", "收件角色名称"))
        item = self.tableWidget_info.verticalHeaderItem(0)
        item.setText(_translate("Form", "剩余账号"))
        item = self.tableWidget_info.verticalHeaderItem(1)
        item.setText(_translate("Form", "完成账号"))
        item = self.tableWidget_info.verticalHeaderItem(2)
        item.setText(_translate("Form", "封禁"))
        item = self.tableWidget_info.verticalHeaderItem(3)
        item.setText(_translate("Form", "中途中断"))
        item = self.tableWidget_info.verticalHeaderItem(4)
        item.setText(_translate("Form", "进入游戏失败"))
        item = self.tableWidget_info.horizontalHeaderItem(0)
        item.setText(_translate("Form", "数量"))
        self.label.setText(_translate("Form", "待选任务"))
        __sortingEnabled = self.listWidget_daixuanrenwu.isSortingEnabled()
        self.listWidget_daixuanrenwu.setSortingEnabled(False)
        item = self.listWidget_daixuanrenwu.item(0)
        item.setText(_translate("Form", "混沌地牢2次"))
        item = self.listWidget_daixuanrenwu.item(1)
        item.setText(_translate("Form", "扔蓝紫书和卡片"))
        item = self.listWidget_daixuanrenwu.item(2)
        item.setText(_translate("Form", "领取邮件"))
        item = self.listWidget_daixuanrenwu.item(3)
        item.setText(_translate("Form", "工会捐献"))
        item = self.listWidget_daixuanrenwu.item(4)
        item.setText(_translate("Form", "兑换魔方票"))
        item = self.listWidget_daixuanrenwu.item(5)
        item.setText(_translate("Form", "邮寄材料"))
        self.listWidget_daixuanrenwu.setSortingEnabled(__sortingEnabled)
        self.pushButton_allAdd.setText(_translate("Form", "全部添加"))
        self.pushButton_add.setText(_translate("Form", "添加任务"))
        self.pushButton_del.setText(_translate("Form", "删除任务"))
        self.pushButton_delAll.setText(_translate("Form", "删除全部"))
        self.pushButton_up.setText(_translate("Form", "上移任务"))
        self.pushButton_down.setText(_translate("Form", "下移任务"))
        self.label_2.setText(_translate("Form", "已选任务"))
        self.pushButton_open_source_file.setText(_translate("Form", "打开日志文件"))
        self.pushButton_open_account_file.setText(_translate("Form", "打开账号文件"))
        self.pushButton_start.setText(_translate("Form", "启动F8"))
        self.pushButton_stop.setText(_translate("Form", "停止F11"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "主功能"))
        self.window_tab.setTabText(self.window_tab.indexOf(self.tab_6), _translate("Form", "主页"))
        item = self.acc_state_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "账号"))
        item = self.acc_state_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "密码"))
        item = self.acc_state_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "大区"))
        item = self.acc_state_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "服务器"))
        item = self.acc_state_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "装备等级"))
        item = self.acc_state_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "混沌副本"))
        item = self.acc_state_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "金币"))
        item = self.acc_state_table.horizontalHeaderItem(7)
        item.setText(_translate("Form", "记录时间"))
        self.search_btn.setText(_translate("Form", "查找"))
        self.window_tab.setTabText(self.window_tab.indexOf(self.tab_7), _translate("Form", "账号状态"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">只支持英文</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">账号格式</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">用户名--密码--大区--小区--要滚的角色数量</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">大区：欧中写c，美西写w，美东写e（全部小写）；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">小区必须写全称，大小写字母不能错；如果不知道可以乱写，自动选上次进入过的小区；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">角色数量直接写数字，把要刷的角色放在前面。</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">钓鱼</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">钓鱼放w，撒网放e;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">提前买好鱼竿放在背包里，会自动维修</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">混沌地牢</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">药放F1；</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">只进入游戏</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">将按照账号列表依次切换账号并进入游戏，进入游戏后，按END键结束当前账号，切换下一个账号</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">坐车模式</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">在“只进入游戏”的基础上，增加了自动点击确定、自动跳过副本动画</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">我想刷3个账号，第一个账号刷5个角色，第二第三个账号刷9个角色，同时需要自动判断混沌之门的开启时间并进入，还要清空每个角色的混沌地牢气息并为每个角色领取邮件怎么办？</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">勾选“滚号”，“滚角色”，“混沌之门”，点击“保存配置”；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已选任务中放入“混沌地牢２次”，“领邮件”，从上到下执行；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">账号文件中，写入要跑的３个账号，每个一行写好角色数量，例如第一个账号写５；<br />然后点击开始就可以了。</p></body></html>"))
        self.window_tab.setTabText(self.window_tab.indexOf(self.tab_2), _translate("Form", "如何使用"))
